### ISSUE TITLE
plans to mint a release?

### ISSUE THREAD

**Issue by jeacott1** [gnl42/JiraConnector#13]
Hi all,
 thanks for the effort going on here! 
I'm wondering how far from a release version this project might be?

**Comment by gnl42** [comment]
Hi (just me now :),
   I think I'm beaten down all/most of the migration bugs I introduced in converting the code to maven.
I'm running the master (4.0.1) branch on my work computer so if any issues crop up, it will be there (caught a couple already).

I have to figure out how to do a release, right now I have no idea how the mechanism works. Still stumbling in the dark here, but hopefully soon.

**Comment by gnl42** [comment]
I'm also just starting upgrading the jira-rest-client-java library to the latest version (5.24 from 1.1-ide-m09) so I'm undecided if I should wait until that is done

**Comment by gnl42** [comment]
Hi, 
  it took a bit longer that I thought but I think my fork is ready for prime time.

https://gnl42.github.io/JiraConnector-update

   George
