### ISSUE TITLE
Jira Cloud doesn't show 'Assigned to' value in People section

### ISSUE THREAD

**Issue by gnl42** [gnl42/JiraConnector#23]
Does show up in the head though

**Comment by jeacott1** [comment]
it actually sets/resets the assigned user whenever I make any change - to the wrong user!
it also doesn't allow me to actually set the assigned user. if I try, the website reverts to unassigned whilst the plugin shows someone else's name in the header and nobody in the People:Assigned to: field.

it would be great if this was fixed, without it I cant update anything jira via eclipse.

**Comment by gnl42** [comment]
Hmm, not sure what is going on here. I haven't seen this behaviour with my instance so I'll have to explore it.

As a workaround, if you click on the browser icon in the upper right of the tab it will take you to the web page and you can make the changes there. When you refresh the issue in eclipse you should the right values

   George

**Comment by jeacott1** [comment]
@gnl42 thank you.
actually the view in browser workaround doesnt work.
I get a "Browser not supported by Jira"  - so I need to deal with jira in an external browser to make changes anyway.
I'm still super grateful to still be able to link and track issues with mylyn/jira. I really can't understand why mylyn was never more popular - perhaps people never knew it existed?

thanks again for keeping this plugin working.

**Comment by gnl42** [comment]
Hmm, interesting.

Just out of curiosity, what's your system and browser/version?

Have you tried changing the default browser for Eclipse?

**Comment by jeacott1** [comment]
@gnl42 
windows 10 pro, and no I haven't tried changing the default browser for eclipse  -I didn't even realise it was an option!
typically I'm using chrome or brave as a desktop browser though.

**Comment by gnl42** [comment]
@jeacott1 
I just realized I forgot to ask you what version of Jira you are using?

It struck me last night that I am seeing a similar problem against my cloud server.

You might be interested in this article on how make Eclipse use Edge for its internal browser:
https://www.modumind.com/2021/05/12/bringing-chromium-to-eclipse-rcp/

**Comment by jeacott1** [comment]
@gnl42 I'm also using cloud jira.
thanks for the link, I'll take a look.

**Comment by gnl42** [comment]
Sigh, starting to think I'm partially dyslexic.

So the problem is that with the Cloud API, Atlassian changed how users are identified. Used to be by account name, now by a "addressId".

I have an idea on how to address the old and the new, and I am looking at it.
Hopefully I will have a fix in the near future.
