### ISSUE TITLE
Long running search times out

### ISSUE THREAD

**Issue by sinhote** [gnl42/JiraConnector#34]
Hi,

First of all, let me congratulate you on your effort to bring the Atlassian Mylyn connector back! It's something I've been longing for a long time!

I've downloaded it and configured my company's JIRA server, but I constantly get a timeout error when I try to download the task list. FYI, I'm currently working from home and using a VPN, so I need to define a proxy in Eclipse, but I could configure and test the server connection without issues, and I could correctly pull a custom issue filter from the server, too (so it seems the connection works).

The error reads: 

```20,000 milliseconds timeout on connection http-outgoing-2 [ACTIVE]```

Let me know if you need any more details.

**Comment by sinhote** [comment]
Hi,

It turns out that it works with a filter returning less results, so I guess this is a question of increasing the timeout or making it configurable.

**Comment by gnl42** [comment]
Hi,
that's "good" news at least, easier to change.
If you run the same, or similar query through the Web UI how long does it take?

There should be a stack trace with the error if you open it. Can you add it

**Comment by gnl42** [comment]
Hi, 
I was able to trigger the error myself using my company server.
I'll see what I can do

**Comment by gnl42** [comment]
HI,
  I've fixed the timeout issue. It is now 10 minutes (some forgotten code in the migration).

If you are expecting a ton of issues you may want to take a look at the 'Search Results' on the Repository Settings popup:

![image](https://user-images.githubusercontent.com/66577321/176990492-0ddc86a7-f156-4133-a3b5-004b509a5c8d.png)

**Comment by sinhote** [comment]
Hey, 

Sorry for not responding to this. Thanks for fixing it so quickly! I got the latest version and it works like a charm. Keep up the good work! Thanks a million!
