### ISSUE TITLE
Support for JDK 17 or higher required for Eclipse 2022-12

### ISSUE THREAD

**Issue by Mito173** [gnl42/JiraConnector#49]
First of all: many thanks for continuing to maintain the Jira Eclipse Connector, this was a great relief since Atlassian abandoned it and their latest version stopped working for me last year. 

Next challenge now, though: Had to switch to Eclipse 2022-12 due to another Plugin, which is mandatory for me. 
Now, when installing the JiraConnector 
from https://gnl42.github.io/JiraConnector-update 
in a clean Eclipse eclipse-jee-2022-12-R-win32-x86_64
I get the following error in the log after restart:

FrameworkEvent ERROR:
org.osgi.framework.BundleException: Could not resolve module: me.glindholm.connector.eclipse.bamboo.ui [926]
  Unresolved requirement: Require-Bundle: me.glindholm.connector.eclipse.ui
    -> Bundle-SymbolicName: me.glindholm.connector.eclipse.ui; bundle-version="4.3.0.v20221217-0902"; singleton:="true"
       me.glindholm.connector.eclipse.ui [934]
         Unresolved requirement: Require-Bundle: me.glindholm.connector.eclipse.commons.ui
           -> Bundle-SymbolicName: me.glindholm.connector.eclipse.commons.ui; bundle-version="4.3.0.v20221217-0902"; singleton:="true"
              me.glindholm.connector.eclipse.commons.ui [929]
                Unresolved requirement: Require-Bundle: org.eclipse.mylyn.tasks.ui
                  -> Bundle-SymbolicName: org.eclipse.mylyn.tasks.ui; bundle-version="3.25.2.v20200814-0512"; singleton:="true"
                     org.eclipse.mylyn.tasks.ui [959]
                       Unresolved requirement: Require-Bundle: org.eclipse.mylyn.commons.notifications.feed; bundle-version="1.0.0"
                         -> Bundle-SymbolicName: org.eclipse.mylyn.commons.notifications.feed; bundle-version="1.17.2.v20200813-0821"; singleton:="true"
                            org.eclipse.mylyn.commons.notifications.feed [943]
                              No resolution report for the bundle.         Unresolved requirement: Require-Bundle: org.eclipse.mylyn.tasks.ui
           -> Bundle-SymbolicName: org.eclipse.mylyn.tasks.ui; bundle-version="3.25.2.v20200814-0512"; singleton:="true"
  Unresolved requirement: Require-Bundle: me.glindholm.connector.eclipse.commons.ui
    -> Bundle-SymbolicName: me.glindholm.connector.eclipse.commons.ui; bundle-version="4.3.0.v20221217-0902"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.tasks.ui; bundle-version="[3.2.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.mylyn.tasks.ui; bundle-version="3.25.2.v20200814-0512"; singleton:="true"
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.mylyn.commons.notifications.feed [osgi.identity; osgi.identity="org.eclipse.mylyn.commons.notifications.feed"; type="osgi.bundle"; version:Version="1.17.2.v20200813-0821"; singleton:="true"] because it is exposed to package 'javax.xml.bind' from resources javax.xml.bind [osgi.identity; osgi.identity="javax.xml.bind"; type="osgi.bundle"; version:Version="2.2.0.v201105210648"] and jakarta.xml.bind [osgi.identity; type="osgi.bundle"; version:Version="2.3.3.v20221112-0806"; osgi.identity="jakarta.xml.bind"] via two dependency chains.

Chain 1:
  org.eclipse.mylyn.commons.notifications.feed [osgi.identity; osgi.identity="org.eclipse.mylyn.commons.notifications.feed"; type="osgi.bundle"; version:Version="1.17.2.v20200813-0821"; singleton:="true"]
    require: (&(osgi.wiring.bundle=javax.xml.bind)(bundle-version>=2.2.0))
     |
    provide: osgi.wiring.bundle: javax.xml.bind
  javax.xml.bind [osgi.identity; osgi.identity="javax.xml.bind"; type="osgi.bundle"; version:Version="2.2.0.v201105210648"]

Chain 2:
  org.eclipse.mylyn.commons.notifications.feed [osgi.identity; osgi.identity="org.eclipse.mylyn.commons.notifications.feed"; type="osgi.bundle"; version:Version="1.17.2.v20200813-0821"; singleton:="true"]
    require: (&(osgi.wiring.bundle=com.sun.xml.bind)(bundle-version>=2.2.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.3.3.v20221112-0806"; osgi.wiring.bundle="com.sun.xml.bind"
  com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20221112-0806"]
    import: (&(osgi.wiring.package=javax.xml.bind)(&(version>=2.3.3)(!(version>=2.3.4))))
     |
    export: osgi.wiring.package: javax.xml.bind
  jakarta.xml.bind [osgi.identity; type="osgi.bundle"; version:Version="2.3.3.v20221112-0806"; osgi.identity="jakarta.xml.bind"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

Any chance to fix this?

Thanks in advance and kind regards,
Michael

**Comment by gnl42** [comment]
Hi Michael,
   alas it is an issue with Mylyn itself, not the connector. Mylyn hasn't been updated in 2.5 years and has fallen behind the changes to Eclipse itself. The good news is that the project is being revived so a new release should be out in the near future.

In the meantime, what you have to do is find a copy of com.sun.xml.bind_2.2.0.v20201118-1845.jar and place it in the eclipse/plugins folder
[com.sun.xml.bind_2.2.0.v20201118-1845.jar.zip](https://github.com/gnl42/JiraConnector/files/10414553/com.sun.xml.bind_2.2.0.v20201118-1845.jar.zip)

George

**Comment by Mito173** [comment]
Hi George,

thanks a lot for the info and the workaround - which solved the issue for me for now! 
You saved my day! :-)

Wish you a nice weekend!

Kind regards,
Michael
