### ISSUE TITLE
Unable to connect to Jira repo with Access token

### ISSUE THREAD

**Issue by agagelis** [gnl42/JiraConnector#51]
I am trying to connect to my Jira repository (on Cloud) but this exception is thrown: 

` me.glindholm.connector.eclipse.internal.jira.core.service.JiraException: java.util.concurrent.ExecutionException: RestClientException{statusCode=Optional[403], ErrorCollections=[ErrorList [status=403, errorMessages=[], errors={}]]}`
![image](https://user-images.githubusercontent.com/12830402/234568550-1cfdddd6-fff7-46ab-af0a-c47587e0ac85.png)

I also tried to connect with my redentials, and could not succeed either.
Eclipse Version : 2022-12 (4.26.0)

Is there any chance , the problem is due to this...??
![image](https://user-images.githubusercontent.com/12830402/234569124-5639eb39-3046-4e99-9f2c-61ede4b03fc5.png)

**Comment by gnl42** [comment]
Hi @agagelis,
 the token length would make no difference. It's just a string as far as the code is concerned.

The 403 would suggest that the server hasn't been configured for REST calls.

Could you try something like this in a private browser window:
`https://192.168.0.120:9283/rest/api/2/user?username=gnl`
and see what you get back?

thanks
George

**Comment by agagelis** [comment]
Hello George, 

It seems that you are right. Here are my results.
![image](https://user-images.githubusercontent.com/12830402/234804665-2716c27a-89e0-4410-b5ac-5a0a338ea835.png)
and after changing username with accountId..

![image](https://user-images.githubusercontent.com/12830402/234804914-b425559d-b006-4f6b-9164-73897043efe3.png)

**Comment by agagelis** [comment]
I made it work . 
I just had to use the API token as password and NOT select the "use Access Token" checkbox!!!!
![image](https://user-images.githubusercontent.com/12830402/234831113-5b2271e9-1217-4da3-b31d-a7143f7366e9.png)

So I am closing the issue! 
Thanks for your support!

**Comment by gnl42** [comment]
Sigh, right. Jira Cloud uses the token in a different way than Jira 9
