### ISSUE TITLE
Problems after migration to Jira Cloud

### ISSUE THREAD

**Issue by Jules1337dev** [gnl42/JiraConnector#58]
Hello George, 

everything worked fine, until we migrated to Jira cloud with SSO. I generated an access token in Jira and wanted to switch to Server URL with the access token, but after validation i get following error. 

May u can help? 
![image](https://github.com/gnl42/JiraConnector/assets/84089388/adfe2609-6815-4409-b925-94539d75e08a)

Thanks in advance!
Julian

**Comment by Jules1337dev** [comment]
I can provide the error log:
![image](https://github.com/gnl42/JiraConnector/assets/84089388/4126e859-ec72-4157-a56d-16946841c266)

**Comment by gnl42** [comment]
Hi Julian,
   With Jira Cloud authentication is with UserId/Token. Somewhat counter-intuitive I know :(

Hope this helps

George

**Comment by Jules1337dev** [comment]
Hi George,

ah now it works, thank u :) All good, the main thing is that it works now :)

Since i updated mylyn i got the following error when i start eclipse. Its not your connector but maybe u know a solution here as well? :)
An internal error occurred during: "Task List Indexer".
Could not load codec 'Lucene95'. Did you forget to add lucene-backward-codecs.jar?

But Mylyn works fine and the connector as well. I installed all things that were available with mylyn...

Thanks!

**Comment by gnl42** [comment]
Hi Julian,
   there have been other reports to the Mylyn list about Lucene95. One solution seems to be:
   
   "Solved this by deleting all files in eclipse-workspace/.metadata/.mylyn/.taskListIndex and restarting Eclipse."
   
   hope this helps

   George

**Comment by Jules1337dev** [comment]
Hi George,

It worked for me too. Thanks for taking care of it! 

BR
Julian

**Comment by rgurley** [comment]
I had the same problem, but finally figured it out. Maybe update the README.md?

To configure Jira Cloud:
Server is https://your-company.atlassian.net/
Label is whatever you want
User ID is your username (email)
Password is your generated access token, leave the Use Access Token Authentication unchecked!
