### ISSUE TITLE
Installation from update site does not work any more (at least  in eclipse 2024-06) 

### ISSUE THREAD

**Issue by temaleva** [gnl42/JiraConnector#60]
Trying to install connector (both ways marketplace or direct) in eclipse 2024-06 receive following error

The following solutions are not available: JiraConnector 5.0.0 (id=me.glindholm.connector.eclipse.feature.group, site=https://gnl42.github.io/JiraConnector-update/)

It looks like update site has no connector any more.

**Comment by temaleva** [comment]
As an workaround: must be installed manually.

**Comment by gnl42** [comment]
Hmm, that would explain why the number of install dropped dramatically back in February.

Yes, manual install using https://gnl42.github.io/JiraConnector-update/ is the workaround. 

I'll try and figure out what's wrong with the install button process

**Comment by temaleva** [comment]
> Hmm, that would explain why the number of install dropped dramatically back in February.
> 
> Yes, manual install using https://gnl42.github.io/JiraConnector-update/ is the workaround.
> 
> I'll try and figure out what's wrong with the install button process

No, sorry, I mean with manual install - copy jars locally on disc. Installation via update Site does  not work at all.

**Comment by gnl42** [comment]
I should have been clearer:

Help->Install New Software->Add

**Comment by temaleva** [comment]
Ok, thank you. Works this this way, I have been trying with drag&drop

**Comment by gnl42** [comment]
Thanks for complaining :)

I'll have to figure why the drag&drop stopped working

**Comment by gnl42** [comment]
Marketplace setup wasn't updated to match the code base refactor back in February.

It's working now. Thanks for pointing out the problem to me, @temaleva
