### ISSUE TITLE
Spent time is not ajusted automatically on Worklog

### ISSUE THREAD

**Issue by temaleva** [gnl42/JiraConnector#61]
No matter the fact, time tracking track time spent within Eclipse is activated in Mylyn Task settings, Time spent value in work log is never adjusted automatically and every time zero. 
The last time I've seen it working was the original Atlasian  connector version. 

If there is any known reason for that? Could it be fixed somehow?

**Comment by gnl42** [comment]
@temaleva It's working with version 5.1.0 now

**Comment by temaleva** [comment]
> @temaleva It's working with version 5.1.0 now

Thank you a lot. 
I am afraid I could not really understand how it could working with version 5.1.0 if have already this version in eclipse since long time. I believe I need to update something before it works.

**Comment by gnl42** [comment]
Hmm, I have a feeling I missed an commit somewhere.

Try updating again. I just pushed out a 5.1.1 version

**Comment by temaleva** [comment]
It works now. 
I have to manually remove version 5.0.0 which still was in plugins folder as well.

**Comment by gnl42** [comment]
I'm glad to hear you were able to straighten it out.

I'm a bit worried why it was such a problem for you though. Hopefully it wasn't any of my project cleanups that messed it up for you
